### ISSUE TITLE
Minor cosmetics

### ISSUE THREAD

**Issue by dougludlow** [rasmusjp/umbraco-multi-url-picker#7]
Hey, thanks a ton for this property editor. The url picker from uComponents was awesome, but as it isn't available for Umbraco 7, this is a great alternative.

I was thinking about making some minor cosmetic changes and wanted to know what you thought.
- [x] Hide the move handle when there's only one item. (#8)
- [x] Align the node icon and name so that when the item is hovered, the underlines meet.
- [x] Gracefully handle when the recycling bin is chosen (do nothing instead of trying to get the id and throwing an error). (#13)
- [x] When a url is picked, but no title was entered, show the url in the picker list. (#14)
